FROM adoptopenjdk/openjdk8:centos
RUN curl https://bintray.com/sbt/rpm/rpm > bintray-sbt-rpm.repo
RUN mv bintray-sbt-rpm.repo /etc/yum.repos.d/
RUN yum install -y sbt
COPY PlaySampleApp/ /opt/PlaySampleApp
RUN cd opt/PlaySampleApp
RUN sbt compile
CMD sbt run